---
users:
  eman:
    name: "Eman"
    groups: [docker]
    ssh_key: eman.pub
  alan:
    name: "Alan"
    groups: [docker]
    ssh_key: alan.pub
  chinenye:
    name: "Chinenye"
    groups: [docker]
    ssh_key: chinenye.pub
  abhi:
    name: "Abhishek"
    groups: [docker]
    ssh_key: abhi.pub
  sahithi:
    name: "Sahithi"
    groups: [docker]
    ssh_key: sahithi.pub
  jonathan:
    name: "Jonathan"
    groups: [docker]
    ssh_key: jonathan.pub
