---
users:
  eman:
    name: "Eman"
    groups: [docker]
    ssh_key: eman.pub
  chinenye:
    name: "Chinenye"
    groups: [docker]
    ssh_key: chinenye.pub
  abhi:
    name: "Abhishek"
    groups: [docker]
    ssh_key: abhi.pub
  jonathan:
    name: "Jonathan"
    groups: [docker]
    ssh_key: jonathan.pub
  damian: 
    name: "Damian"
    groups: [docker]
    ssh_key: damian.pub
  ravleen: 
    name: "Ravleen"
    groups: [docker]
    ssh_key: ravleen.pub
  william:
    name: "William"
    groups: [docker]
    ssh_key: boulton.pub
  zeren:
    name: "Zeren"
    groups: [docker]
    ssh_key: zeren.pub
  alex:
    name: "Alex"
    groups: [docker]
    ssh_key: alex.pub
